#!/bin/sh
case "$1" in
  start)
    echo "Starting Security Sensor System"
    modprobe security_mod
    major=$(awk '$2=="security_sensor" {print $1}' /proc/devices)
    if [ -n "$major" ]; then
        rm -f /dev/security_sensor
        mknod /dev/security_sensor c $major 0
        chmod 666 /dev/security_sensor
    fi
    # Start the socket server in background
    start-stop-daemon -S -n security_app -a /usr/bin/security_app -b
    ;;
  stop)
    echo "Stopping Security Sensor System"
    start-stop-daemon -K -n security_app
    rmmod security_mod
    rm -f /dev/security_sensor
    ;;
esac
exit 0
